import {lend} from "../models/lend.model";

export class ListServices {
  books: lend[] = [
    { name: "Livre 1",
      description: " description du livre 1 ",
      isLend: true},
    { name: "Livre 2",
      description: " description du livre 2 ",
      isLend: false},
    { name: "Livre 3",
      description: " description du livre 3 ",
      isLend: false},
    { name: "Livre 4",
      description: " description du livre 4",
      isLend: true},
    { name: "Livre 5",
      description: " description du livre 5",
      isLend: false},
    { name: "Livre 6",
      description: " description du livre 6 ",
      isLend: false},
    { name: "Livre 7",
      description: " description du livre 7",
      isLend: false},
    { name: "Livre 8",
      description: " description du livre 8 ",
      isLend: false},
    { name: "Livre 9",
      description: " description du livre 9 ",
      isLend: false},
    { name: "Livre 10",
      description: " description du livre 10",
      isLend: false},
    { name: "Livre 11",
      description: " description du livre 11",
      isLend: true},
    { name: "Livre 12",
      description: " description du livre 12 ",
      isLend: false},
    { name: "Livre 13",
      description: " description du livre 13",
      isLend: false},
    { name: "Livre 14",
      description: " description du livre 14",
      isLend: false},
    { name: "Livre 15",
      description: " description du livre 15",
      isLend: false},
    { name: "Livre 16",
      description: " description du livre 16",
      isLend: false},
    { name: "Livre 17",
      description: " description du livre 17",
      isLend: false},
    { name: "Livre 18",
      description: " description du livre 18",
      isLend: false},
    { name: "Livre 19",
      description: " description du livre 19",
      isLend: false},
    { name: "Livre 20",
      description: " description du livre 20",
      isLend: false},

  ];

  cds: lend[] = [
    { name: "CD 0",
      description: " description du CD ",
      isLend: false},
    { name: "CD1",
      description: " description du CD 1 ",
      isLend: false},
    { name: "CD 2",
      description: " description du CD 2",
      isLend: false},
    { name: "CD 3",
      description: " description du CD 3",
      isLend: false},
    { name: "CD 4",
      description: " description du CD 4",
      isLend: false},
    { name: "CD 5",
      description: " description du CD 5",
      isLend: false},
    { name: "CD 6",
      description: " description du CD 6",
      isLend: false},
    { name: "CD 7",
      description: " description du CD 7",
      isLend: false},
    { name: "CD 8",
      description: " description du CD 8",
      isLend: false},
    { name: "CD 9",
      description: " description du CD 9",
      isLend: false},
    { name: "CD 10",
      description: " description du CD 10",
      isLend: false},
    { name: "CD 11",
      description: " description du CD 11",
      isLend: false},
    { name: "CD 12",
      description: " description du CD 12",
      isLend: false},
    { name: "CD 13",
      description: " description du CD 13",
      isLend: false},
    { name: "CD 14",
      description: " description du CD 14",
      isLend: false},
    { name: "CD 15",
      description: " description du CD 15",
      isLend: false},
    { name: "CD 16",
      description: " description du CD 16",
      isLend: false},
    { name: "CD 17",
      description: " description du CD 17",
      isLend: false},
    { name: "CD 18",
      description: " description du CD 18",
      isLend: false},
    { name: "CD 19",
      description: " description du CD 19",
      isLend: false},

  ];
}
